Neos:
  Form:
    presets:
      default:
        formElementTypes:
          'MIWeb.Neos.Form:FileUpload':
            superTypes:
              'Neos.Form:FormElement': true
              'Neos.Form:FileUpload': true
            implementationClassName: 'MIWeb\Neos\Form\FormElements\FileUpload'
            properties:
              allowedExtensions:
                - pdf
                - doc
          'MIWeb.Neos.Form:ContentReference':
            superTypes:
              'Neos.Form:FormElement': true
            implementationClassName: 'MIWeb\Neos\Form\FormElements\ContentReference'
            properties:
              parent: '/site'
              type: 'Neos.Neos:Page'
              dataType: 'Node'

  Neos:
    fusion:
      autoInclude:
        'MIWeb.Neos.Form': TRUE